
name: DEPLOY TO STAGING

on:
  push:
    branches:
      - develop

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
      - run: yarn install
      - name: Building the project
      - run: cp -r * .public
      - run: mv .public public
        with:
          args: deploy --only hosting
view rawdeploy.yml hosted with ❤ by GitHub